### ISSUE TITLE
ugly checkout path

### ISSUE THREAD

**Issue by cultcom** [debops-contrib/ansible-roundcube#15]
```
roundcube__git_checkout: '{{ roundcube__www + "/sites/" + roundcube__domain[0] + "/public" }}'
```
this leads to "/srv/www/roundcube/sites/w/public/" which is unneeded complex. Why "domain[0]"? In my case "w" because the domain starts with "webmail" instead of "roundcube".

nginx already  creates "/srv/www/sites/localhost/public", so why not "/srv/www/sites/roundcube/public"?

```
roundcube__git_checkout: '{{ nginx_www + "/sites/roundcube/public" }}'
```

**Comment by ganto** [comment]
What is your value of `roundcube__domain`? Back in the days when I wrote this role, I copied that principle from `debops.owncloud`. The idea was, that all the Web application roles behave similar. In `defaults/main.yml` the variable `roundcube__domain` is defined as a list of domains:
```
# .. envvar:: roundcube__domain
#
# List of domains which will be used to access the roundcube instance.
roundcube__domain: [ 'roundcube.{{ ansible_domain }}' ]
```

I don't know all the reasoning behind that but I also never saw that as a problem... Maybe @drybjed can explain this better.

**Comment by drybjed** [comment]
At the beginning I planned for the variables like these to allow for multiple domains, but after some time I noticed issues like this one showing up when people used the wrong value type. Now I'm opting to support both cases (one FQDN as a string and multiple FQDNs as a list) so that this doesn't show up as an issue when the value is configured as an inventory. Other roles like `debops.nginx` support this usage as well, so you can pass values to other roles would explicitly wrapping them.

In this case I would go with this setup (variables from Ansible local facts should be checked if they are defined, here I use them in an explicit form for readability):
```yaml
# defaults/main.yml

# The main domain of the installation
roundcube__domain: '{{ ansible_local.core.domain }}'

# Webmail FQDN address
roundcube__fqdn: 'mail.{{ roundcube__domain }}'

# nginx WWW directory
roundcube__www: '{{ ansible_local.nginx.www }}'

# Git checkout path and similar paths
roundcube__git_checkout: '{{ roundcube__www + "/" + roundcube__user + "/sites/" +
                             (roundcube__fqdn if roundcube__fqdn is string else roundcube__fqdn[0]) +
                             "/public" }}'
```
